image:
  file: Dockerfile
ports:
- port: 8050
  onOpen: open-preview
- port: 8888
  onOpen: open-browser
tasks:
- command: pyenv global 3.7.4 &&
           chmod +x envconfig.sh 
  
vscode:
  extensions:
    # for R Extension - https://www.gitpod.io/docs/languages/r/#r-extension
    - Ikuyadeu.r@1.2.1:z5vr1v1bfS++U/aHLSXQ6Q==
